namespace RepositoryPattern;

/// <summary>
/// CONCRETE REPOSITORY IMPLEMENTATION - In-Memory Storage
///
/// This is a concrete implementation of IRepository that stores data in memory.
/// In a real application, you'd have implementations that use:
/// - SQL databases (via Entity Framework Core, Dapper, ADO.NET)
/// - NoSQL databases (MongoDB, CosmosDB, DynamoDB)
/// - External APIs
/// - File system
/// - Cache (Redis, Memcached)
///
/// The Repository pattern allows you to swap implementations without changing
/// the code that uses the repository. This is the power of abstraction!
///
/// WHY IN-MEMORY FOR THIS DEMO?
/// - No database setup required
/// - Fast and simple
/// - Perfect for demonstrating the pattern
/// - Easy to unit test
/// </summary>
public class InMemoryProductRepository : IRepository<Product>
{
    // In-memory storage - in a real app, this would be a database
    private readonly List<Product> _products = new();

    // Thread-safe ID generation
    private int _nextId = 1;
    private readonly object _lockObject = new();

    /// <summary>
    /// Constructor that optionally seeds initial data.
    /// </summary>
    public InMemoryProductRepository(bool seedData = false)
    {
        if (seedData)
        {
            SeedData();
        }
    }

    /// <summary>
    /// Get a product by its ID.
    /// Returns null if not found.
    ///
    /// In a real database implementation, this would be:
    /// - EF Core: _context.Products.FindAsync(id)
    /// - Dapper: _connection.QuerySingleOrDefaultAsync<Product>("SELECT * FROM Products WHERE Id = @Id", new { Id = id })
    /// </summary>
    public Task<Product?> GetByIdAsync(int id)
    {
        var product = _products.FirstOrDefault(p => p.Id == id);
        return Task.FromResult(product);
    }

    /// <summary>
    /// Get all products.
    ///
    /// In a real database implementation:
    /// - EF Core: _context.Products.ToListAsync()
    /// - Dapper: _connection.QueryAsync<Product>("SELECT * FROM Products")
    /// </summary>
    public Task<IEnumerable<Product>> GetAllAsync()
    {
        // Return a copy to prevent external modification
        return Task.FromResult<IEnumerable<Product>>(_products.ToList());
    }

    /// <summary>
    /// Find products that match a predicate.
    ///
    /// Example usage:
    ///   repository.FindAsync(p => p.Category == "Electronics")
    ///   repository.FindAsync(p => p.Price > 100)
    ///
    /// In a real database implementation:
    /// - EF Core: _context.Products.Where(predicate).ToListAsync()
    /// Note: With EF Core, you'd want to use Expression<Func<T, bool>> instead of Func<T, bool>
    /// so the predicate can be translated to SQL (IQueryable). This is a simplified version.
    /// </summary>
    public Task<IEnumerable<Product>> FindAsync(Func<Product, bool> predicate)
    {
        var results = _products.Where(predicate).ToList();
        return Task.FromResult<IEnumerable<Product>>(results);
    }

    /// <summary>
    /// Add a new product.
    ///
    /// Key points:
    /// - Assigns a new ID automatically
    /// - Thread-safe ID generation
    /// - In a real DB, the ID would be auto-generated by the database
    ///
    /// In a real database implementation:
    /// - EF Core: _context.Products.AddAsync(entity); await _context.SaveChangesAsync();
    /// - Dapper: _connection.ExecuteAsync("INSERT INTO Products (...) VALUES (...)", entity)
    /// </summary>
    public Task AddAsync(Product entity)
    {
        // Thread-safe ID assignment
        lock (_lockObject)
        {
            entity.Id = _nextId++;
        }

        _products.Add(entity);
        Console.WriteLine($"[Repository] Added: {entity}");

        return Task.CompletedTask;
    }

    /// <summary>
    /// Update an existing product.
    ///
    /// In a real database implementation:
    /// - EF Core: _context.Products.Update(entity); await _context.SaveChangesAsync();
    /// - Dapper: _connection.ExecuteAsync("UPDATE Products SET ... WHERE Id = @Id", entity)
    /// </summary>
    public Task UpdateAsync(Product entity)
    {
        var existing = _products.FirstOrDefault(p => p.Id == entity.Id);

        if (existing == null)
        {
            throw new InvalidOperationException($"Product with ID {entity.Id} not found");
        }

        // Update properties (in a real app, you might use AutoMapper or reflection)
        existing.Name = entity.Name;
        existing.Category = entity.Category;
        existing.Price = entity.Price;
        existing.StockQuantity = entity.StockQuantity;
        existing.IsActive = entity.IsActive;

        Console.WriteLine($"[Repository] Updated: {existing}");

        return Task.CompletedTask;
    }

    /// <summary>
    /// Delete a product by ID.
    ///
    /// In a real database implementation:
    /// - EF Core: var entity = await _context.Products.FindAsync(id); _context.Products.Remove(entity); await _context.SaveChangesAsync();
    /// - Dapper: _connection.ExecuteAsync("DELETE FROM Products WHERE Id = @Id", new { Id = id })
    /// </summary>
    public Task DeleteAsync(int id)
    {
        var product = _products.FirstOrDefault(p => p.Id == id);

        if (product == null)
        {
            throw new InvalidOperationException($"Product with ID {id} not found");
        }

        _products.Remove(product);
        Console.WriteLine($"[Repository] Deleted: {product}");

        return Task.CompletedTask;
    }

    /// <summary>
    /// Check if a product exists.
    /// </summary>
    public Task<bool> ExistsAsync(int id)
    {
        var exists = _products.Any(p => p.Id == id);
        return Task.FromResult(exists);
    }

    /// <summary>
    /// Count total number of products.
    /// </summary>
    public Task<int> CountAsync()
    {
        return Task.FromResult(_products.Count);
    }

    /// <summary>
    /// Seed initial data for demonstration purposes.
    /// In a real application, this would be in a database migration/seed script.
    /// </summary>
    private void SeedData()
    {
        _products.AddRange(new[]
        {
            new Product { Id = _nextId++, Name = "Laptop", Category = "Electronics", Price = 999.99m, StockQuantity = 50, IsActive = true },
            new Product { Id = _nextId++, Name = "Mouse", Category = "Electronics", Price = 29.99m, StockQuantity = 200, IsActive = true },
            new Product { Id = _nextId++, Name = "Keyboard", Category = "Electronics", Price = 79.99m, StockQuantity = 150, IsActive = true },
            new Product { Id = _nextId++, Name = "T-Shirt", Category = "Clothing", Price = 19.99m, StockQuantity = 300, IsActive = true },
            new Product { Id = _nextId++, Name = "Jeans", Category = "Clothing", Price = 49.99m, StockQuantity = 100, IsActive = true },
            new Product { Id = _nextId++, Name = "Book", Category = "Books", Price = 14.99m, StockQuantity = 75, IsActive = true },
            new Product { Id = _nextId++, Name = "Headphones", Category = "Electronics", Price = 149.99m, StockQuantity = 0, IsActive = false }
        });

        Console.WriteLine($"[Repository] Seeded {_products.Count} products");
    }
}
